# Generated by Django 3.2.8 on 2021-11-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orguser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
