# Generated by Django 3.2.8 on 2021-11-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211105_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='orguser',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
