# Generated by Django 3.2.8 on 2021-11-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211105_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='expected_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
    ]
