# Generated by Django 3.2.8 on 2021-11-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_invoicehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicehistory',
            name='username',
            field=models.CharField(max_length=25),
        ),
    ]
