# Generated by Django 3.2.8 on 2021-11-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_invoicehistory_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='has_stripe_account',
            field=models.BooleanField(default=False),
        ),
    ]
