# Generated by Django 3.2.8 on 2021-11-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_orguser_has_stripe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='orguser',
            name='stripe_account_id',
            field=models.CharField(default='NO STRIPE ACCOUNT', max_length=25),
        ),
    ]
