# Generated by Django 3.2.8 on 2021-12-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.CharField(default='NO CATEGORIES', max_length=150),
        ),
    ]
