# Generated by Django 3.2.8 on 2021-12-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_budget_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='title',
            field=models.CharField(default='NO TITLE', max_length=25),
        ),
    ]
