# Generated by Django 3.2.8 on 2021-12-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_budget_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(default='NO TITLE', max_length=25, unique=True),
        ),
    ]
