# Generated by Django 3.2.8 on 2021-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_budget_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='organization',
        ),
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.CharField(default='NO BUDGET', max_length=25),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
