# Generated by Django 3.2.8 on 2021-12-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_budget_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
